POST  https://api.movies.developer.nomoredomains.rocks/signup
Content-Type: application/json

{
  "name": "Developer",
  "email": "1234@yandex.ru",
  "password": "test"
}

###

POST  https://api.movies.developer.nomoredomains.rocks/signin
Content-Type: application/json

{
  "email": "1234@yandex.ru",
  "password": "test"
}

###

GET https://api.movies.developer.nomoredomains.rocks/users/me
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2M2M2ZjlhZmYzMmE1Y2FlNTRhMzE5MmQiLCJpYXQiOjE2NzM5ODQ0MzYsImV4cCI6MTY3NDU4OTIzNn0.N7o4X_rWpjCFVu10aiEfcx83ApoFU09xsqVN5W4fm9M

###

PATCH https://api.movies.developer.nomoredomains.rocks/users/me
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2M2M2ZjlhZmYzMmE1Y2FlNTRhMzE5MmQiLCJpYXQiOjE2NzM5ODQ0MzYsImV4cCI6MTY3NDU4OTIzNn0.N7o4X_rWpjCFVu10aiEfcx83ApoFU09xsqVN5W4fm9M

{
  "name": "Oleg",
  "email": "1235@yandex.ru"
}

###


GET https://api.movies.developer.nomoredomains.rocks/movies
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2M2M2ZjlhZmYzMmE1Y2FlNTRhMzE5MmQiLCJpYXQiOjE2NzM5ODQ0MzYsImV4cCI6MTY3NDU4OTIzNn0.N7o4X_rWpjCFVu10aiEfcx83ApoFU09xsqVN5W4fm9M

###

POST  https://api.movies.developer.nomoredomains.rocks/movies
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2M2M2ZjlhZmYzMmE1Y2FlNTRhMzE5MmQiLCJpYXQiOjE2NzM5ODQ0MzYsImV4cCI6MTY3NDU4OTIzNn0.N7o4X_rWpjCFVu10aiEfcx83ApoFU09xsqVN5W4fm9M

{
  "country": "США",
  "director": "Стивен Кайак",
  "duration": 61,
  "year": "2010",
  "description": "В конце 1960-х группа «Роллинг Стоунз», несмотря на все свои мегахиты и сверхуспешные концертные туры, была разорена. Виной всему — бездарный менеджмент и драконовское налогообложение в Британии. Тогда музыканты приняли не самое простое для себя решение: летом 1971 года после выхода альбома «Stiсky Fingers» они отправились на юг Франции записывать новую пластинку. Именно там, на Лазурном Берегу, в арендованном Китом Ричардсом подвале виллы Неллькот родился сборник «Exile on Main St.», который стал лучшим альбомом легендарной группы.",
  "image": "https://www.filmposters.com/images/posters/19471.jpg",
  "trailerLink": "https://www.youtube.com/watch?v=UXcqcdYABFw",
  "thumbnail": "https://www.filmposters.com/images/posters/19471.jpg",
  "movieId": "1",
  "nameRU": "«Роллинг Стоунз» в изгнании",
  "nameEN": "Stones in Exile"
}

###

DELETE https://api.movies.developer.nomoredomains.rocks/movies/63c6fa17f32a5cae54a31934
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2M2M2ZjlhZmYzMmE1Y2FlNTRhMzE5MmQiLCJpYXQiOjE2NzM5ODQ0MzYsImV4cCI6MTY3NDU4OTIzNn0.N7o4X_rWpjCFVu10aiEfcx83ApoFU09xsqVN5W4fm9M
###
